### ISSUE TITLE
An option to make the default color scheme less blinding

### ISSUE THREAD

**Issue by andymboyle** [themarshallproject/klaxon#109]
Hey folks,

The default color scheme is blindingly bright, and not only makes me feel sick looking at it, but I know it makes others feel the same, too. I am sure that this is perhaps a unique opinion, and not exactly on the highest of priorities for you fine people right now, but the default Klaxon settings are so bright and hard to see.

Yeah we can go in and change them and all that jazz, but this is just a thought: Perhaps think of making the default color scheme a little less loud? Or don't listen to me at all, for I am a dumb dumb. Thanks!

**Comment by tommeagher** [comment]
Hi Andy! Thanks for submitting this. We're glad to hear you're putting Klaxon to use. This is an interesting issue you raise. If you all want to tackle some customization options for the color scheme and documentation, we'd be glad to take a look at a pull request and merge it into the code base.

**Comment by zzolo** [comment]
I support this idea.  Though I do enjoy the red, it's not actually great to look at in the long run.

See the WCAG contrast analysis, which mostly fails:
http://webaim.org/resources/contrastchecker/?fcolor=ff0b3a&bcolor=ffffff

Looking into making the color a variable that can be swapped out, looks hard as its in a lot of places:
https://github.com/themarshallproject/klaxon/search?utf8=%E2%9C%93&q=ff0b3a&type=

So, maybe there is a way to have themes, or otherwise, its just a matter of changing the default which wouldn't be too hard.

**Comment by matsaman** [comment]
Is this tied to the https://newsklaxon.org/ homepage color scheme? Honestly, & truly not for nothing, when I first loaded that page, I said to myself /out loud/ "ugh... give me a fscking break...".

**Comment by andymboyle** [comment]
@matsaman Yup. The default color scheme is incredibly hard to look at.

**Comment by tommeagher** [comment]
@matsaman, @andymboyle. Totally understand if the colors don't work for you or your organization. If you want to take a crack at adding options to customize it, we'd be happy to review a pull request that would benefit other Klaxon users.

**Comment by matsaman** [comment]
@tommeagher I haven't quite cracked open your software before, but in the case of newsklaxon.org and anything with which that page shares code, you could literally just do a global find & replace of `#ff0b3a` with virtually anything else and improve the situation for every last person that exists in the universe. Even simply a darker shade would be better.

**Comment by zzolo** [comment]
The question is whether the color should be straight changed or if this should become an configuration option.  The former is just a find and replace.  The latter is much harder, since the color is used in many different types of places.

Given the difficulty of adding a configuration option for this, I would 👍  to updating the default.

**Comment by ivarvong** [comment]
@tommeagher @GabeIsman This might be a good fit for [CSS Custom Properties](https://developer.mozilla.org/en-US/docs/Web/CSS/--*) – the lowest lift might be an ENV var that injects the custom property into a `<style>` tag on the page. 

The platform CSS would then pull from custom property first with a fallback to the current color.

[Browser support](https://caniuse.com/css-variables/embed) is pretty good.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (7 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
