### ISSUE TITLE
Regular user can edit other users

### ISSUE THREAD

**Issue by zzolo** [themarshallproject/klaxon#133]
If I am a regular/non-admin user, then I can edit the names and emails of other users.  Is this intended?

**Comment by tommeagher** [comment]
@zzolo that was intentional with the original design, yes. There were no admin users, and the idea was that any user could subscribe someone else in their newsroom to an alert. We were particularly thinking of reporters signing their editors up to watch a specific page and vice versa. Now, with admin users added in v 0.2.5, we may want to rethink that a bit.

**Comment by tommeagher** [comment]
With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 7 years old) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
