### ISSUE TITLE
Heroku Setup and SendGrid issues

### ISSUE THREAD

**Issue by dslamancmic** [themarshallproject/klaxon#406]
I'm having some problems getting things working on the Heroku platform.
I'm not receiving the initial email to start setting up the admin portion of the application.

A brief history of what I've done so far:

I setup a free Heroku account
I setup a SendGrid Account
I deployed the Heroku project
Did the scheduler config

I opened one ticket with SendGrid and that didn't get very far.
I opened a new one after seeing that the SendGrid Heroku add-on creates an account along with installing.
To see this go under the Heroku project, Settings, Reveal Config Vars, SENDGRID_USERNAME
The username to give to SendGrid is something like app11111111111@heroku.com.
Then SendGrid support was able to authorize that account.
THEN clicking the link from Heroku into the SendGrid add-on brought up the page and I could create a sender and an API Key.
Previously, it would be a 403 forbidden page.
It would also say that my account was not authorized for that add-on after removing and re-adding it.

In the SendGrid account page (under the Heroku account, not my account)
I setup a single sender account.
I generated an API key and put that in the Config Vars in Heroku.
"SENDGRID_API_KEY" - "SG.K_......."
No change in functionality.

In the SendGrid account section I don't see any stats for recent emails, so I suspect that the email is not making it into that Add-on to try sending.

I suspect that my issue is now figuring out how to get the SendGrid Heroku add-on "linked" with the application.

**Comment by tommeagher** [comment]
Hi @dslamancmic. Thank you for this very thorough ticket. It seems that SendGrid is changing how it provisions accounts, and the functionality of its API, which is wrecking some havoc on our little project that has been running pretty well for about 4 years before this. So we're working on some fixes to smooth this out, but it may be a few weeks until they're available. In the meantime, your issues looks very similar to #404. I'm guessing that SendGrid is now forbidding emails to be sent from a different email address than the one on your Heroku/Sendgrid account. You might want to give the solution from the user in #404 a try and see if that helps. Otherwise, if you can wait a few weeks, we hope to have a new release that deals with this before the end of the year.

**Comment by dslamancmic** [comment]
Confirmed. The solution in 404 worked. Thanks. I'm not sure how I didn't see that issue when I looked through the support options.

**Comment by tommeagher** [comment]
@dslamancmic I'm really glad to hear it. I'll close this issue as a duplicate for now and we'll concentrate on using #404 as a guide to improving our setup. Thanks again!
