### ISSUE TITLE
Can't log in via bookmarklet

### ISSUE THREAD

**Issue by mikejanssen** [themarshallproject/klaxon#459]
I'm using the Klaxon bookmarklet in Chrome 89.0.4389.90 (Mac) and am getting a 422 "Rejected. You might not have access" message, even when I'm logged in. I saw an earlier issue reported here and tried toggling the third-party cookie option in Chrome preferences, but that didn't work.

**Comment by tommeagher** [comment]
@mikejanssen do you have any better success in another browser, out of curiosity?

**Comment by mikejanssen** [comment]
@tommeagher Same problem in Safari.

**Comment by tommeagher** [comment]
Hi @mikejanssen, thanks. We'll have to look into this. One additional question, did this work for you at some point and then it stopped working, or has it always been an issue since you launched your instance of Klaxon?
And what version of Klaxon are you running?

**Comment by mikejanssen** [comment]
Yes, it used to work. Uh sorry but how do I find out what version I'm running?

**Comment by tommeagher** [comment]
This is something we want to surface in Klaxon but for now you have to peek in your Github fork for it. Look in this URL, swapping out your username where we have "themarshallproject": https://github.com/themarshallproject/klaxon/releases

That lists all the releases you have in your version, and you can see what is the most recent.

**Comment by mikejanssen** [comment]
I get a "page not found" when I do that.

**Comment by tommeagher** [comment]
Is your fork of Klaxon in a public Github repo?

**Comment by GabeIsman** [comment]
My best guess is that 1) you're on older version of Klaxon (if you haven't updated in the last year or so then this is true) or 2) you're application is in an environment without https. Are you on Heroku? If not, that might be the issue. There's some explanation of this here: https://github.com/themarshallproject/klaxon/pull/380 but the TL;DR is that browsers are moving away from allowing third party cookies on insecure connections.

**Comment by mikejanssen** [comment]
@GabeIsman Yep, my version is older than a year. So I should just update?

**Comment by mikejanssen** [comment]
I followed the "applying upgrades" instructions through "You'll only have to do all of this one time to set up the pipeline." I don't think the version I'm on is below 0.2.0 so I didn't do that part. But I'm still having the same issue with the bookmarklet, in both Safari and Chrome.

**Comment by Wowfunhappy** [comment]
Hi, I'm experiencing this and I only just set up my Klaxon instance this weekend, so it's definitely up-to-date! I'm also on Heroku.

**Comment by tnehil** [comment]
I'm running into this same problem in both Firefox and Chrome, working from a fresh install from today. The only exotic thing about my case is I'm using a custom domain name. But everything seemed to be working fine -- I can log in to the main dashboard, create users, etc. But when I try to use the bookmarklet I get asked to log in (even when already logged in), and when I submit the login form I get the 422 error described at the top of this issue.

**Comment by tnehil** [comment]
I decided to dig into this a little more by running Klaxon locally. When I try to log in to the bookmarklet there, I get the more detailed error:

```ActionController::InvalidAuthenticityToken in SessionsController#create 
Can't verify CSRF token authenticity.```

Following [this thread](https://stackoverflow.com/questions/35181340/rails-cant-verify-csrf-token-authenticity-when-making-a-post-request) on StackOverflow, I changed `protect_from_forgery with: :exception` in `app/application_controller.rb` to `protect_from_forgery with: :null_session`. This fixed this error, in that when I would try to log in to the bookmarklet, I'd get the "email sent" page, and since I'm working locally it would open the local file with the mocked up email. But the iframe is then just stuck on "email sent", and refreshing just causes the login screen to reappear.

It seems like the basic issue here is that the bookmarklet page isn't able to read the session information from  local storage — I shouldn't even be seeing the login screen there since I have already logged in. 

I may try to work on this further (though this is my first time working with Rails) but I wanted to post what I found in case it sparked any ideas from anyone.

**Comment by tnehil** [comment]
For what it's worth, I was able to fix the bookmarklet for myself by doing away with the iframe and instead opening the bookmarklet in a new window. I did this by editing `app/views/embed/inject.js.erb`. There was a commented out line for opening a new window, which I uncommented, and then commented out all the code for setting up the iframe. To wit:

```
  var src = editorURL + "?url=" + encodeURIComponent(getCanonicalURL());
  // var iframe = document.createElement('iframe');
  // iframe.setAttribute('src', src);
  // iframe.setAttribute('id', 'klaxon-bookmarklet-iframe');
  // iframe.setAttribute('frameborder', 0);
  // iframe.style.top = '0px';
  // iframe.style.right = '0px';
  // iframe.style.width = '300px';
  // iframe.style.height = (window.innerHeight)+'px';
  // iframe.style.position = 'fixed';
  // iframe.style.zIndex = 2147483647; // just a big number, hopefully big enough
  // document.body.appendChild(iframe);
  // document.body.setAttribute('cursor', 'grab')
  var iframe = window.open(src, "Klaxon", "width=200,height=200");
```

For whatever reason, opening in a new window instead of an iframe allowed klaxon to correctly see that I was logged in. 

Using a new window instead of an iframe in the same window required some other changes, like adding the event listeners to `iframe.opener` instead of `window`, changing `var matchText = document.querySelector(selector).innerText;` to `var matchText = iframe.opener.document.querySelector(selector).innerText;` and changing `iframe.contentWindow.postMessage(json, postMessageDomain);` to `iframe.postMessage(json, postMessageDomain);`.

**Comment by tommeagher** [comment]
Hi all. With the recent release of [Klaxon Cloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), we're going back and revisiting old issues that we're not going to pursue or support as we consider any future development of the original standalone Klaxon. This one (almost 3 years old now) falls in that bucket. Thanks for the contributions and discussions on this, but we'll close it as WONTFIX.
