### ISSUE TITLE
Klaxon "feed" page not updating

### ISSUE THREAD

**Issue by chrismp** [themarshallproject/klaxon#792]
Klaxon this week stopped emailing me updates as they happen. Instead, I have to go to the "Watching" page, then click "latest change" before it updates the "Feed" page and emails me. How do I fix this?

I'm using this version of Klaxon, which has worked well till the past week: https://github.com/chrismp/klaxon/commit/6a654b3cceb8545687c33e57b467505309a66563

**Comment by tommeagher** [comment]
Hi @chrismp. Sorry for the slow response while we've had people out the last few weeks. It's hard to say what caused your Klaxon to stop working, though that is a really old version. You could [try upgrading to the latest version](https://github.com/themarshallproject/klaxon?tab=readme-ov-file#applying-upgrades-as-the-project-develops). You should also note that as of earlier this year, we are [no longer developing or supporting the self-hosted Klaxon code](https://github.com/themarshallproject/klaxon?tab=readme-ov-file#get-emailed-when-a-website-changes). You're welcome to fork the codebase and keep it running for your own organization. We're also encouraging people who don't want to invest in that maintenance to look at [KlaxonCloud](https://www.documentcloud.org/app?q=#add-ons/MuckRock/Klaxon), the new add-on from DocumentCloud that has very similar capabilities, built into the DocumentCloud platform. 
As a result, because we're no longer supporting this tool, we can't help you with this issue.
