### ISSUE TITLE
Protect against bogus canonical urls

### ISSUE THREAD

**Issue by GabeIsman** [themarshallproject/klaxon#86]
Some sites (http://www.deathpenaltyinfo.org/alabama-0, e.g.) provide `<link rel="canonical">` tags with bad data (in this case, just the relative path and not the full canonical url). Klaxon currently uses the `rel="canonical"` or the `<meta name="og:url">` or the `location.href` in that order. Should we validate the alternate urls before relying on them? Is there a compelling reason to not just always use the current url?

@ivarvong Do you remember what the original motivation for using the canonical url was?

**Comment by ivarvong** [comment]
Validation is a good idea, even if just for {scheme, host, path}. Hitting that URL endpoint and getting a non-empty reply would be better, perhaps.

The canonical check reduces duplicate records due to different query params on the same URL, ie tracking news articles with different social share UTM params.

**Comment by GabeIsman** [comment]
That's a good point about duplicates. I think simple validation should be enough. I imagine the venn diagram of sites that have canonical url tags but screw them up is not huge. I guess you never know.
